config/routes.rb
Rails.application.routes.draw do

  resources :band_names

  get 'vote_for' => 'votes#for', as: :vote_for
  resources :votes

  resources :people

  get 'search/:query' => 'quotes#search', as: :query
  get 'search' => 'quotes#search', as: :search
  get 'mpq' => 'quotes#add_mpq', as: :add_mpq
  resources :quotes

  devise_for :users
  get 'config' => 'users#show', as: :user
  post 'config' => 'users#update', as: :update_user

  get 'static_pages/home'

  root 'static_pages#home'

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :attribution, class_name: 'Person', foreign_key: :attribution
  belongs_to :multi_part_quote, dependent: :destroy
  has_many :votes

  validates_presence_of :text, :attribution

  SEARCH_VECTORS = [:attributed_to, :contains, :bands_named, :named_by, :authored_by]
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json
  QUOTES_PER_PAGE = 20
  MPQ = MultiPartQuote

  include FilterHelper

  def index
    @filter = {}
    raw_filter = params[:filter] || {}
    raw_filter.map{|k, v| @filter[k.to_sym] = filter(raw_filter, k)}

    @sort = sort_from_params(params)
    order = order_from_sort(@sort)

    @quotes = MPQ.joins(:quotes).includes(:quotes).order(order).uniq

    if(@filter[:author])
      authors = Person.where('people.name ILIKE ?', "#{@filter[:author]}")
      @quotes = @quotes.where(author: authors)
    end

    if(@filter[:attribution])
      people = Person.where('people.name ILIKE ?', "#{@filter[:attribution]}")
      @quotes = @quotes.where(quotes: {attribution: people})
    end

    @quotes = @quotes.where('quotes.text ILIKE ?', "%#{@filter[:content]}%") if(@filter[:content])
    @quotes = @quotes.where('quotes.context ILIKE ?', "%#{@filter[:context]}%") if(@filter[:context])
    @quotes = @quotes.page(params[:page]).per(QUOTES_PER_PAGE)

    respond_with(@quotes)
  end

  def show
    respond_with(@quote)
  end

  def new
    @quote = MPQ.new
    @quote.quotes << Quote.new
    respond_with(@quote)
  end

  def edit
  end

  def add_mpq
  end

  def create
    mpqp = quote_params
    errors = []

    @quote = MPQ.create(author: mpqp[:author], score: 0)

    # Don't process quotes if MPQ is not correct
    if(@quote.errors.any?)
      errors += @quote.errors.full_messages
    else
      # Process each quote
      mpqp[:quotes].each_with_index do |qp, index|
        quote = Quote.create(text: qp[:text], attribution: qp[:attribution], context: qp[:context], order: index)
        @quote.quotes << quote

        # Shut it down if any of them have errors
        if(quote.errors.any?)
          errors += quote.errors.full_messages
          @quote.quotes.each{|q| q.destroy}
          break
        end
      end
    end

    # Check that at least one quote was created
    if(@quote.quotes.size == 0)
      @quote.destroy
      @quote.quotes << Quote.new
      errors << 'Fill in at least one quote, you dope!'
    end

    # Update person quote counts
    if(errors.empty?)
      @quote.quotes.each do |q|
        q.attribution.update_attribute(:num_quotes, q.attribution.quotes.count) if(q.attribution)
      end
    else
      flash.now[:error] = errors.join('  ')
    end

    #respond_with(@quote)
    respond_to do |format|
      if(errors.size > 0)
        format.html {render :new}
      else
        format.html {render :show}
      end
    end
  end

  def update
    @quote.update(quote_params)
    respond_with(@quote)
  end

  def destroy
    @quote.destroy
    respond_with(@quote)
  end

  def search
    @query = params[:query]
    @results = {}
    results_per_category = 10

    @results[:attributed_to] = MPQ.joins(quotes: :attribution).where('people.name ILIKE ?', "%#{@query}%")
    @results[:authored_by] = MPQ.joins(:author).where('people.name ILIKE ?', "%#{@query}%")
    @results[:contains] = MPQ.joins(:quotes).where('quotes.text ILIKE ?', "%#{@query}%")
    @results[:bands_named] = BandName.where('band_names.name ILIKE ?', "%#{@query}%")
    @results[:named_by] = BandName.joins(:person).where('people.name ILIKE ?', "%#{@query}%")

    Quote::SEARCH_VECTORS.each do |vector|
      @results[vector] = @results[vector].page(params[vector]).per(results_per_category) if(@results[vector])
    end
  end

  private

    include PeopleHelper

    def set_quote
      @quote = MPQ.find(params[:id])
    end

    def quote_params
      p_dup = personify_params(params)
      quotes = []

      params[:quote].each do |quote|
        next if((quote[:text].nil? || quote[:text].empty?) && (quote[:attribution].nil? || quote[:attribution].empty?))
        q = personify_params(quote)
        q.delete(:context) if(q[:context].nil? || q[:context].strip.empty?)
        quotes << q
      end

      return {quotes: quotes, author: p_dup[:author]}
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_add_quote.erb
  <div class="col-xs-12">
    <%= link_to 'Add A Quote!', new_quote_path, role: :button, class: 'btn btn-primary btn-lg quote-button' %>
  </div>

app/views/quotes/_filter.erb
<% filters ||= [] %>
<% current_filter ||= {} %>
<% form_path ||= quotes_path %>

<div class="col-xs-12">
  <% if current_filter.empty? %>
      <p>No filter - just like my words.</p>
  <% else %>
      <p>
        <% current_filter.each do |key, val| %>
            <% next if val.nil? %>
            <span class="filter-key"><%= key.to_s.humanize %></span>
            <span class="filter-val"><%= val.to_s %></span>
        <% end %>
      </p>
  <% end %>

  <%= form_tag(form_path, class: 'form', role: 'form', method: :get) do %>
      <div class="row">
        <% filters.each do |filter| %>
            <div class="col-xs-12 col-sm-6">
              <div class="form-group">
                <%= text_field_tag("filter[#{filter}]", current_filter[filter], class: 'form-control', placeholder: filter.to_s.humanize) %>
              </div>
            </div>
        <% end %>

        <div class="col-xs-12 col-sm-6">
          <div class="form-group">
            <%= submit_tag('Apply Filter', class: 'btn btn-primary') %>
            <%= link_to('Clear Filter', form_path, class: 'btn btn-danger') %>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/quotes/_form.html.erb
<%# form_for(@quote, html: { class: "form-horizontal", role: "form" }) do |f| %>
<%= form_tag(quotes_path, class: "form-horizontal", role: "form") do %>

    <table id="quote_forms" class="table-responsive table table-striped table-bordered">
      <% @quote.quotes.each do |quote| %>
          <%= render partial: 'quote_form', locals: {quote: quote} %>
      <% end %>
    </table>

    <div class="form-group">
      <%= label_tag :author, 'Who Are You?', class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= text_field_tag :author, @quote.author ? @quote.author.name : (current_user && current_user.person ?  current_user.person.name : ''), class: "form-control", placeholder: 'Anonymous' %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= link_to 'Add Another Part', add_mpq_path, class: 'btn btn-primary', remote: true %>
        <%= submit_tag 'Create Quote', class: "btn btn-primary" %>
      </div>
    </div>
<% end %>

app/views/quotes/_index.erb
<% quotes ||= [] %>
<% width ||= 6 %>
<% pagination_param ||= :page %>
<% query ||= nil %>

  <div class="col-xs-12">
    <% begin %>
        <%= paginate(quotes, param_name: pagination_param) if(!quotes.is_a?(Array)) %>
    <% rescue %>
    <% end %>
  </div>

  <% quotes.each_with_index do |quote, i| %>
      <%= render partial: 'quotes/show', locals: {quote: quote, width: width, query: query, num: i} %>
  <% end %>

<% if quotes.size == 0 %>
    <%= render 'no_results' %>
<% end %>

app/views/quotes/_no_results.erb
<div class="col-xs-12">
  <h2>Nothing To See Here...</h2>
  <p>Move along.</p>
</div>

app/views/quotes/_quote_form.html.erb
<tr>
  <td>
    <div class="form-group">
      <%= label_tag 'quote[][text]', 'The Quote', class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= text_area_tag 'quote[][text]',  quote.text, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= label_tag 'quote[][attribution]', 'Who Said It?', class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= text_field_tag 'quote[][attribution]', quote.attribution ? quote.attribution.name : '', class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
        <%= label_tag 'quote[][context]', 'In What Context?', class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= text_field_tag 'quote[][context]', quote.context, placeholder: 'Optional', class: "form-control" %>
        </div>
      </div>
    </div>
  </td>
</tr>

app/views/quotes/_score.erb
<p class="score">( <%= score >= 0 ? '+' : ''%><%=score%> )</p>

app/views/quotes/_show.erb
<% quote ||= nil %>
<% width ||= 6 %>
<% mpq = quote %>
<% query ||= nil %>
<% num ||= 1 %>

<% if mpq %>
    <div class="col-xs-12 col-sm-<%=width%> <%= num % 2 == 0 ? 'clear' : ''%>">
      <div class="quote-box">
        <table class="table table-bordered table-responsive">
          <tbody>
          <tr>
            <td colspan="3" class="table-overflow">
              <div class="watermark">
                <span>“</span>
              </div>
              <div class="watermark-content">
                <% mpqs = mpq.quotes.order(order: :asc) %>
                <% if true %>
                    <% mpqs.each do |q| %>
                        <p class="quote"><%= highlight q.text, query || (@filter ? @filter[:content] : nil) %></p>
                        <p class="attribution">
                          <%= display_person(q.attribution, query || (@filter ? @filter[:attribution] : nil)) %><%= q.context ? "<span class=context>, #{highlight(q.context, query || @filter ? @filter[:context] : nil)}</span>".html_safe : '' %>
                        </p>
                    <% end %>
                <% else %>
                    <%# Old MPQ Style... seems unnecessary now %>
                    <table class="quote-table">
                      <% mpqs.each do |q| %>
                          <tr class="quote-row">
                            <td class="quote-col left">
                              <span class="attribution quote">
                                <%= display_person(q.attribution, query || (@filter ? @filter[:attribution] : nil)) %><%= q.context ? "<span class=context>, #{highlight(q.context, query || @filter ? @filter[:context] : nil)}</span>".html_safe : '' %>
                              </span>
                            </td>
                            <td class="quote-col right">
                              <span class="quote"><%= highlight q.text, query || (@filter ? @filter[:content] : nil) %></span>
                            </td>
                          </tr>
                      <% end %>
                    </table>
                <% end %>
                <% score = mpq.score.nil? ? 0 : mpq.score %>
              </div>
            </td>
          </tr>
          <tr>
            <td class="vote up-<%=mpq.id%>">
              <%= render partial: 'quotes/upvote', locals: {value: 1, mpq: mpq, vote: current_user ? current_user.votes.where(multi_part_quote: mpq).first : nil} %>
            </td>
            <td>
              <span class="author">Submitted by: <%= display_person(mpq.author, query || (@filter ? @filter[:author] : nil)) %></span>
              <div class="score-<%=mpq.id%>">
                <%= render partial: 'quotes/score', locals: {score: score} %>
              </div>
            </td>
            <td class="vote dn-<%=mpq.id%>">
              <%= render partial: 'quotes/upvote', locals: {value: -1, mpq: mpq, vote: current_user ? current_user.votes.where(multi_part_quote: mpq).first : nil} %>
            </td>
          </tr>
          </tbody>
        </table>
      </div>
    </div>
<% end %>

app/views/quotes/_sort.erb
<% orders ||= [] %>
<% current_order ||= {} %>
<% path ||= :quotes_path %>

<% orders.each do |order| %>
    <div class="col-sm-3 col-xs-6">
      <% direction = current_order[order] ? current_order[order] : :desc %>
      <% new_direction = direction == :asc ? :desc : :asc %>

      <%= link_to self.send(path, {order: {order => new_direction}, filter: @filter}), class: "btn btn-default btn-block" do %>
          <% icon = current_order[order] ? (current_order[order] == :asc ? 'glyphicon-arrow-up' : 'glyphicon-arrow-down') : 'glyphicon-sort' %>
          <span class="glyphicon <%= icon %>"></span>
          <%= order.to_s.humanize %>
          <span class="glyphicon <%=icon%>"></span>
      <% end %>
    </div>
<% end %>

app/views/quotes/_upvote.erb
<% disabled ||= false %>
<% mpq ||= nil %>
<% band ||= nil %>

<% if disabled %>
    <div class="full">
      <span class="glyphicon <%=value > 0 ? 'glyphicon-plus' : 'glyphicon-minus'%>"></span>
    </div>
<% else %>
    <% if current_user.nil? %>
        <div class="full">
          <span class="glyphicon <%=value > 0 ? 'glyphicon-plus' : 'glyphicon-minus'%>"></span>
        </div>
    <% elsif vote %>
        <% if((vote.value > 0 && value > 0) || (vote.value < 0 && value < 0)) %>
            <%= link_to vote_for_path(user_id: current_user ? current_user.id : nil, quote_id: mpq ? mpq.id : nil, band_name_id: band ? band.id : nil, value: value), remote: true do %>
                <div class="full <%= value > 0 ? 'up-voted' : 'dn-voted'%>">
                  <span class="glyphicon <%=value > 0 ? 'glyphicon-plus' : 'glyphicon-minus'%>"></span>
                </div>
            <% end %>
        <% else %>
            <%= link_to vote_for_path(user_id: current_user ? current_user.id : nil, quote_id: mpq ? mpq.id : nil, band_name_id: band ? band.id : nil, value: value), remote: true do %>
                <div class="full">
                  <span class="glyphicon <%=value > 0 ? 'glyphicon-plus' : 'glyphicon-minus'%>"></span>
                </div>
            <% end %>
        <% end %>
    <% else %>
        <%= link_to vote_for_path(user_id: current_user ? current_user.id : nil, quote_id: mpq ? mpq.id : nil, band_name_id: band ? band.id : nil, value: value), remote: true do %>
            <div class="full">
              <span class="glyphicon <%=value > 0 ? 'glyphicon-plus' : 'glyphicon-minus'%>"></span>
            </div>
        <% end %>
    <% end %>

<% end %>

app/views/quotes/edit.html.erb
<div class="page-header">
  <%= link_to quotes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @quote, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing quote</h1>
</div>

<%= render 'form' %>

app/views/quotes/new.html.erb
<div class="page-header">
  <h1>Record a Gem!</h1>
</div>

<%= render 'form' %>

app/views/quotes/search.erb
<div class="page-header">
  <h1>The Search Results</h1>
</div>

<%# render 'quotes/add_quote' %>

<% num_empty_vectors = 0 %>
<% Quote::SEARCH_VECTORS.each do |vector| %>
    <% if(@results[vector].size == 0) %>
        <% num_empty_vectors += 1 %>
        <% next %>
    <% end %>
    <div class="row">
      <div class="col-xs-12">
        <h2><%=vector.to_s.titleize%> <%=@query%></h2>
        <% if @results[vector].first.is_a?(BandName) %>
            <%= render partial: 'band_names/index', locals: {bands: @results[vector], pagination_param: vector, query: @query} %>
        <% else %>
            <%= render partial: 'quotes/index', locals: {quotes: @results[vector], pagination_param: vector, query: @query} %>
        <% end %>
      </div>
    </div>
<% end %>

<% if(num_empty_vectors == Quote::SEARCH_VECTORS.size) %>
    <div class="row">
      <div class="col-xs-12">
        <h2>Nobody Said It!</h2>
        <p>Your search for "<%=@query%>" turned up zero results.  Search better.  Try harder.</p>
      </div>
    </div>
<% end %>

app/views/quotes/show.html.erb
<div class="page-header">
  <!--
  <%= link_to edit_quote_path(@quote), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  -->
  <h1>Quote</h1>
</div>

<%= render partial: 'quotes/show', locals: {quote: @quote, width: 12} %>