config/routes.rb
Rails.application.routes.draw do

  resources :band_names

  get 'vote_for' => 'votes#for', as: :vote_for
  resources :votes

  resources :people

  get 'search/:query' => 'quotes#search', as: :query
  get 'search' => 'quotes#search', as: :search
  get 'mpq' => 'quotes#add_mpq', as: :add_mpq
  resources :quotes

  devise_for :users
  get 'config' => 'users#show', as: :user
  post 'config' => 'users#update', as: :update_user

  get 'static_pages/home'

  root 'static_pages#home'

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :multi_part_quote
  belongs_to :user
  belongs_to :band_name
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_vote, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @votes = Vote.all
    respond_with(@votes)
  end

  def show
    respond_with(@vote)
  end

  def new
    @vote = Vote.new
    respond_with(@vote)
  end

  def edit
  end

  def create
    @vote = Vote.new(vote_params)
    @vote.save
    respond_with(@vote)
  end

  def update
    @vote.update(vote_params)
    respond_with(@vote)
  end

  def destroy
    @vote.destroy
    respond_with(@vote)
  end

  # Non-CRUD functions
  def for
    @mpq = MultiPartQuote.where(id: params[:quote_id]).first
    @band_name = BandName.where(id: params[:band_name_id]).first
    user = User.find(params[:user_id])
    value = params[:value].to_i
    errors = []

    @vote = @band_name.nil? ? Vote.find_or_create_by(user: user, multi_part_quote: @mpq) : Vote.find_or_create_by(user: user, band_name: @band_name)

    # vote: 1, value: 1, increment: -1
    # vote: 1, value: -1, increment: -2
    # vote: -1, value: 1, increment: +2
    # vote: -1, value: -1. increment: +1
    # vote: 0, value: 1, increment: +1
    # vote: 0, value: -1, increment: -1

    sign = (@vote.value.nil? || @vote.value == 0) ? value : -@vote.value;
    magnitude = (@vote.value && @vote.value != 0 && @vote.value != value) ? 2 : 1;

    @vote.update_attribute(:value, (@vote.value == value) ? 0 : value)
    errors += @vote.errors.full_messages if(@vote.errors.any?)

    updated = @mpq ? @mpq : @band_name

    @score = updated.score + (sign * magnitude)
    updated.update_attribute(:score, @score)
  end

  private
    def set_vote
      @vote = Vote.find(params[:id])
    end

    def vote_params
      params.require(:vote).permit(:user_id, :quote_id, :value)
    end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/votes/_form.html.erb
<%= form_for(@vote, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @vote.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h4>

      <ul>
      <% @vote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :user_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :user_id, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :quote_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :quote_id, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :value, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :value, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/votes/edit.html.erb
<div class="page-header">
  <%= link_to votes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @vote, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing vote</h1>
</div>

<%= render 'form' %>

app/views/votes/index.html.erb
<div class="page-header">
  <%= link_to new_vote_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Vote
  <% end %>
  <h1>Listing votes</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>User</th>
            <th>Quote</th>
            <th>Value</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @votes) do |vote| %>
            <td><%= vote.user_id %></td>
            <td><%= vote.quote_id %></td>
            <td><%= vote.value %></td>
            <td><%= link_to 'Show', vote %></td>
        <td><%= link_to 'Edit', edit_vote_path(vote) %></td>
        <td><%= link_to 'Destroy', vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/votes/new.html.erb
<div class="page-header">
  <%= link_to votes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New vote</h1>
</div>

<%= render 'form' %>

app/views/votes/show.html.erb
<div class="page-header">
  <%= link_to votes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_vote_path(@vote), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show vote</h1>
</div>

<dl class="dl-horizontal">
  <dt>User:</dt>
  <dd><%= @vote.user_id %></dd>

  <dt>Quote:</dt>
  <dd><%= @vote.quote_id %></dd>

  <dt>Value:</dt>
  <dd><%= @vote.value %></dd>

</dl>