config/routes.rb
Rails.application.routes.draw do

  resources :band_names

  get 'vote_for' => 'votes#for', as: :vote_for
  resources :votes

  resources :people

  get 'search/:query' => 'quotes#search', as: :query
  get 'search' => 'quotes#search', as: :search
  get 'mpq' => 'quotes#add_mpq', as: :add_mpq
  resources :quotes

  devise_for :users
  get 'config' => 'users#show', as: :user
  post 'config' => 'users#update', as: :update_user

  get 'static_pages/home'

  root 'static_pages#home'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>The Quote Book</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=0">
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'The Quote Book', root_path, class: 'navbar-brand' %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Quotes <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'All Quotes', quotes_path %></li>
              <li><%= link_to 'Add a Quote', new_quote_path %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Band Names <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'All Band Names', band_names_path %></li>
              <li><%= link_to 'Add a Band Name', new_band_name_path %></li>
            </ul>
          </li>

          <li><%= link_to 'People', people_path %></li>
          <% if !user_signed_in? %>
              <li><%= link_to 'Sign In', new_user_session_path %></li>
          <% else %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'My Account', edit_user_registration_path %></li>
                  <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
          <% end %>

          <!--
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
        -->
        </ul>

        <!--
        <div class="col-sm-3 col-md-3 pull-right">
          <form class="navbar-form" role="search">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search" name="srch-term" id="srch-term">
              <div class="input-group-btn">
                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
              </div>
            </div>
          </form>
        </div>
        -->

        <div class="col-sm-3 col-md-3 pull-right">
          <%= form_tag('/search', method: :get, class: 'navbar-form', role: 'search') do %>
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search" name="query">
              <span class="input-group-btn">
                <button class="btn btn-default" style="height: 34px;" type="submit">
                  <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                </button>
              </span>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </nav>
  <div class="container">

    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name.to_sym == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>